pipeline:
  identifier: Build_Golang_CICD_Tutorial_1686118940042
  name: Build Golang-CICD-Tutorial
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1677651348716
        repoName: satishcloudsec/Golang-CICD-Tutorial
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "Harness Go app"
                      go build
                      go test
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
